#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCH[0]}") && pwd)

rm -rf $HOME/.oh-my-zsh/custom
ln -s $DOTFILES/oh-my-zsh/custom $HOME/.oh-my-zsh/custom

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

rm -rf $HOME/.zshrc
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

rm -rf $HOME/.ideavimrc
ln -s $DOTFILES/php-storm/ideavimrc $HOME/.ideavimrc

mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

